/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Biodata;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ridjal Fathoni
 */
public class frmBiodata extends javax.swing.JFrame {

    /**
     * Creates new form frmBiodata
     */
    public frmBiodata() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtNo = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtNik = new javax.swing.JTextField();
        txtJabatan = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Bebas", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BIODATA    KARYAWAN");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 20, 240, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 890, 90);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(null);
        jPanel4.add(jSeparator2);
        jSeparator2.setBounds(0, 30, 320, 10);

        jLabel2.setText("ALAMAT");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(10, 240, 100, 30);

        jLabel4.setText("ID KARYAWAN");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(10, 40, 100, 30);

        jLabel5.setText("NAMA KARYAWAN");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(10, 80, 100, 30);

        jLabel6.setText("NIK");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(10, 120, 100, 30);

        jLabel7.setText("JABATAN");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(10, 160, 100, 30);

        jLabel8.setText("NO. HP");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(10, 200, 100, 30);

        jPanel3.setLayout(null);

        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel3.add(btnExit);
        btnExit.setBounds(200, 10, 60, 30);

        btnNew.setText("NEW");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jPanel3.add(btnNew);
        btnNew.setBounds(10, 10, 60, 30);

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel3.add(btnSave);
        btnSave.setBounds(70, 10, 60, 30);

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btnDelete);
        btnDelete.setBounds(130, 10, 70, 30);

        jPanel4.add(jPanel3);
        jPanel3.setBounds(20, 350, 270, 50);
        jPanel4.add(txtNo);
        txtNo.setBounds(130, 200, 180, 30);
        jPanel4.add(txtId);
        txtId.setBounds(130, 40, 180, 30);
        jPanel4.add(txtNama);
        txtNama.setBounds(130, 80, 180, 30);
        jPanel4.add(txtNik);
        txtNik.setBounds(130, 120, 180, 30);
        jPanel4.add(txtJabatan);
        txtJabatan.setBounds(130, 160, 180, 30);

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane2.setViewportView(txtAlamat);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(130, 240, 180, 80);

        jLabel9.setText("DETAIL BIODATA");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(10, 4, 190, 20);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 100, 320, 420);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        tblData.setForeground(new java.awt.Color(255, 255, 255));
        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID KARYAWAN", "NAMA KARYAWAN", "NIK", "JABATAN", "NO. HP", "ALAMAT"
            }
        ));
        jScrollPane1.setViewportView(tblData);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(0, 40, 550, 380);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(0, 30, 550, 10);

        jLabel3.setText("BIODATA");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 0, 190, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(330, 100, 550, 430);

        setSize(new java.awt.Dimension(897, 558));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        txtId.setText("");
        txtNama.setText("");
        txtNik.setText("");
        txtJabatan.setText("");
        txtNo.setText("");
        txtAlamat.setText("");
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if ("".equals(txtId.getText()) || "".equals(txtNama.getText())
                || "".equals(txtNik.getText()) || "".equals(txtJabatan.getText()) || "".equals(txtNo.getText()) || "".equals(txtAlamat.getText())) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            String SQL = "INSERT INTO tb_koneksi(id_karyawan,nama_karyawan,nik,jabatam,no_hpmalamat)"
                    + "VALUES('" + txtId.getText() + "','" + txtNama.getText() + "','" + txtNik.getText() + "',"
                    + "'" + txtJabatan.getText() + "','" + txtNo.getText() + "','" + txtAlamat.getText() + "')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int baris = tblData.getSelectedRow();
        if (baris != - 1) {
            String id_karyawan = tblData.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_koneksi WHERE NIS='"+id_karyawan+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terebih Dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
        
        selectData();   
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBiodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBiodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBiodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBiodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBiodata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblData;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtJabatan;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNik;
    private javax.swing.JTextField txtNo;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"id_karyawan","nama_karyawan","nik","jabatan","no_hp","alamat"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tb_koneksi";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {
            while(rs.next()) {
                String id = rs.getString(1);
                String nama = rs.getString(2);
                String nik = rs.getString(3);
                String jabatan = rs.getString(4);
                String no = rs.getString(5);
                String data[] = {id,nama,nik,jabatan,no};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmBiodata.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblData.setModel(dtm);
    }
}
